# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeScreen.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1758, 1018)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.topBarHorizontalLayout = QtWidgets.QHBoxLayout()
        self.topBarHorizontalLayout.setObjectName("topBarHorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topBarHorizontalLayout.addItem(spacerItem)
        self.wanikaniLogo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wanikaniLogo.sizePolicy().hasHeightForWidth())
        self.wanikaniLogo.setSizePolicy(sizePolicy)
        self.wanikaniLogo.setMinimumSize(QtCore.QSize(0, 55))
        self.wanikaniLogo.setBaseSize(QtCore.QSize(0, 0))
        self.wanikaniLogo.setObjectName("wanikaniLogo")
        self.topBarHorizontalLayout.addWidget(self.wanikaniLogo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topBarHorizontalLayout.addItem(spacerItem1)
        self.lessonsLink = QtWidgets.QPushButton(self.centralwidget)
        self.lessonsLink.setObjectName("lessonsLink")
        self.topBarHorizontalLayout.addWidget(self.lessonsLink)
        self.reviewsLink = QtWidgets.QPushButton(self.centralwidget)
        self.reviewsLink.setObjectName("reviewsLink")
        self.topBarHorizontalLayout.addWidget(self.reviewsLink)
        self.levelsLink = QtWidgets.QPushButton(self.centralwidget)
        self.levelsLink.setObjectName("levelsLink")
        self.topBarHorizontalLayout.addWidget(self.levelsLink)
        self.radicalLink = QtWidgets.QPushButton(self.centralwidget)
        self.radicalLink.setObjectName("radicalLink")
        self.topBarHorizontalLayout.addWidget(self.radicalLink)
        self.kanjiLink = QtWidgets.QPushButton(self.centralwidget)
        self.kanjiLink.setObjectName("kanjiLink")
        self.topBarHorizontalLayout.addWidget(self.kanjiLink)
        self.vocabularyLink = QtWidgets.QPushButton(self.centralwidget)
        self.vocabularyLink.setObjectName("vocabularyLink")
        self.topBarHorizontalLayout.addWidget(self.vocabularyLink)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.topBarHorizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.topBarHorizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1736, 885))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayoutScrolling = QtWidgets.QVBoxLayout()
        self.verticalLayoutScrolling.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayoutScrolling.setObjectName("verticalLayoutScrolling")
        self.searchBarHorizontalLayout = QtWidgets.QHBoxLayout()
        self.searchBarHorizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.searchBarHorizontalLayout.setObjectName("searchBarHorizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.searchBarHorizontalLayout.addItem(spacerItem2)
        self.searchBar = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.searchBar.setFrame(True)
        self.searchBar.setObjectName("searchBar")
        self.searchBarHorizontalLayout.addWidget(self.searchBar)
        self.verticalLayoutScrolling.addLayout(self.searchBarHorizontalLayout)
        self.availabilityHorizontalLayout = QtWidgets.QHBoxLayout()
        self.availabilityHorizontalLayout.setObjectName("availabilityHorizontalLayout")
        self.nextReviewAvailable = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.nextReviewAvailable.setFrameShape(QtWidgets.QFrame.Box)
        self.nextReviewAvailable.setAlignment(QtCore.Qt.AlignCenter)
        self.nextReviewAvailable.setObjectName("nextReviewAvailable")
        self.availabilityHorizontalLayout.addWidget(self.nextReviewAvailable)
        self.nextHourAvailable = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.nextHourAvailable.setFrameShape(QtWidgets.QFrame.Box)
        self.nextHourAvailable.setAlignment(QtCore.Qt.AlignCenter)
        self.nextHourAvailable.setObjectName("nextHourAvailable")
        self.availabilityHorizontalLayout.addWidget(self.nextHourAvailable)
        self.nextDayAvailable = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.nextDayAvailable.setFrameShape(QtWidgets.QFrame.Box)
        self.nextDayAvailable.setAlignment(QtCore.Qt.AlignCenter)
        self.nextDayAvailable.setObjectName("nextDayAvailable")
        self.availabilityHorizontalLayout.addWidget(self.nextDayAvailable)
        self.verticalLayoutScrolling.addLayout(self.availabilityHorizontalLayout)
        self.subjectCountHorizontalLayout = QtWidgets.QHBoxLayout()
        self.subjectCountHorizontalLayout.setObjectName("subjectCountHorizontalLayout")
        self.apprenticeCount = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.apprenticeCount.setFrameShape(QtWidgets.QFrame.Box)
        self.apprenticeCount.setAlignment(QtCore.Qt.AlignCenter)
        self.apprenticeCount.setObjectName("apprenticeCount")
        self.subjectCountHorizontalLayout.addWidget(self.apprenticeCount)
        self.guruCount = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.guruCount.setFrameShape(QtWidgets.QFrame.Box)
        self.guruCount.setAlignment(QtCore.Qt.AlignCenter)
        self.guruCount.setObjectName("guruCount")
        self.subjectCountHorizontalLayout.addWidget(self.guruCount)
        self.masterCount = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.masterCount.setFrameShape(QtWidgets.QFrame.Box)
        self.masterCount.setTextFormat(QtCore.Qt.AutoText)
        self.masterCount.setAlignment(QtCore.Qt.AlignCenter)
        self.masterCount.setObjectName("masterCount")
        self.subjectCountHorizontalLayout.addWidget(self.masterCount)
        self.enlightenedCount = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.enlightenedCount.setFrameShape(QtWidgets.QFrame.Box)
        self.enlightenedCount.setAlignment(QtCore.Qt.AlignCenter)
        self.enlightenedCount.setObjectName("enlightenedCount")
        self.subjectCountHorizontalLayout.addWidget(self.enlightenedCount)
        self.burnedCount = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.burnedCount.setFrameShape(QtWidgets.QFrame.Box)
        self.burnedCount.setAlignment(QtCore.Qt.AlignCenter)
        self.burnedCount.setObjectName("burnedCount")
        self.subjectCountHorizontalLayout.addWidget(self.burnedCount)
        self.verticalLayoutScrolling.addLayout(self.subjectCountHorizontalLayout)
        self.levelRadicalVerticalLayout = QtWidgets.QVBoxLayout()
        self.levelRadicalVerticalLayout.setObjectName("levelRadicalVerticalLayout")
        self.levelRadicalProgressionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.levelRadicalProgressionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.levelRadicalProgressionLabel.setObjectName("levelRadicalProgressionLabel")
        self.levelRadicalVerticalLayout.addWidget(self.levelRadicalProgressionLabel)
        self.levelRadicalProgressionItemsLocation = QtWidgets.QHBoxLayout()
        self.levelRadicalProgressionItemsLocation.setObjectName("levelRadicalProgressionItemsLocation")
        self.levelRadicalVerticalLayout.addLayout(self.levelRadicalProgressionItemsLocation)
        self.verticalLayoutScrolling.addLayout(self.levelRadicalVerticalLayout)
        self.levelKanjiVerticalLayout = QtWidgets.QVBoxLayout()
        self.levelKanjiVerticalLayout.setObjectName("levelKanjiVerticalLayout")
        self.levelKanjiProgressionLabels = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.levelKanjiProgressionLabels.setAlignment(QtCore.Qt.AlignCenter)
        self.levelKanjiProgressionLabels.setObjectName("levelKanjiProgressionLabels")
        self.levelKanjiVerticalLayout.addWidget(self.levelKanjiProgressionLabels)
        self.levelKanjiProgressionItemsLocation = QtWidgets.QHBoxLayout()
        self.levelKanjiProgressionItemsLocation.setObjectName("levelKanjiProgressionItemsLocation")
        self.levelKanjiVerticalLayout.addLayout(self.levelKanjiProgressionItemsLocation)
        self.verticalLayoutScrolling.addLayout(self.levelKanjiVerticalLayout)
        self.statsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.statsHorizontalLayout.setObjectName("statsHorizontalLayout")
        self.newUnlockLayout = QtWidgets.QVBoxLayout()
        self.newUnlockLayout.setObjectName("newUnlockLayout")
        self.statsHorizontalLayout.addLayout(self.newUnlockLayout)
        self.criticalConditionLayout = QtWidgets.QVBoxLayout()
        self.criticalConditionLayout.setObjectName("criticalConditionLayout")
        self.statsHorizontalLayout.addLayout(self.criticalConditionLayout)
        self.burnedItemsLayout = QtWidgets.QVBoxLayout()
        self.burnedItemsLayout.setObjectName("burnedItemsLayout")
        self.statsHorizontalLayout.addLayout(self.burnedItemsLayout)
        self.verticalLayoutScrolling.addLayout(self.statsHorizontalLayout)
        self.verticalLayout_12.addLayout(self.verticalLayoutScrolling)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1758, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.wanikaniLogo.setText(_translate("MainWindow", "WaniKani Logo"))
        self.lessonsLink.setText(_translate("MainWindow", "Lessons"))
        self.reviewsLink.setText(_translate("MainWindow", "Reviews"))
        self.levelsLink.setText(_translate("MainWindow", "Levels"))
        self.radicalLink.setText(_translate("MainWindow", "Radicals"))
        self.kanjiLink.setText(_translate("MainWindow", "Kanji"))
        self.vocabularyLink.setText(_translate("MainWindow", "Vocabulary"))
        self.pushButton.setText(_translate("MainWindow", "Account"))
        self.nextReviewAvailable.setText(_translate("MainWindow", "Next Review Available"))
        self.nextHourAvailable.setText(_translate("MainWindow", "Available Next Hour"))
        self.nextDayAvailable.setText(_translate("MainWindow", "Available Next Day"))
        self.apprenticeCount.setText(_translate("MainWindow", "Apprentice Cnt"))
        self.guruCount.setText(_translate("MainWindow", "Guru Cnt"))
        self.masterCount.setText(_translate("MainWindow", "Master Cnt"))
        self.enlightenedCount.setText(_translate("MainWindow", "Enlightened Cnt"))
        self.burnedCount.setText(_translate("MainWindow", "Burned Cnt"))
        self.levelRadicalProgressionLabel.setText(_translate("MainWindow", "Level Radical Progression"))
        self.levelKanjiProgressionLabels.setText(_translate("MainWindow", "Level Kanji Progression"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

